### ISSUE TITLE
Update pagination with contextual component

### ISSUE THREAD

**Issue by jweakley** [wildland/ember-bootstrap-controls#116]
This would be the default for when a single page is available.

**Comment by jweakley** [comment]
So someone could use the following if they wanted to render a `div` with class `nothing` when the pagination had only a single page (1 total item and page size was 25).
```
{{#bootstrap-pagination-nav
  pageNumber=pageNumber
  pageSize=pageSize
  totalPages=totalPages
  moveToPage=(action (mut pageNumber))}}
  <div class='nothing' />
{{/bootstrap-pagination-nav}}

**Comment by Samsinite** [comment]
Started working on inner components that we can yield though this component. As a side effect, it also cleaned up some of this component. The branch is at `contextual-pagination`
