### ISSUE TITLE
ember-prop-type placeholder component

### ISSUE THREAD

**Issue by jweakley** [wildland/ember-bootstrap-controls#144]
This component would be used to help create an automatic way of documenting the live demo.

**Comment by jweakley** [comment]
This would allow us to do something like the following in the live docs:
```
{{prop-docs
  data=data
  propTypes=myComponent.propTypes
  defaultValues=myComponent. getDefaultProps()
}}
```

This component would then render the appropriate inputs per the types that it can and document them. So:
```
  propTypes: {
    foo: PropTypes.string,
    bar: PropTypes.number.isRequired,
    baz: PropTypes.bool
  },
```
Would have
- `{{inputs/-text label="foo" value=data.foo}}`
- `{{inputs/-number label="bar" value=data.bar}}`
- `{{inputs/-checkbox label="baz" value=data.baz}}`

**Comment by harokevin** [comment]
@jweakley do we do this already?
