### ISSUE TITLE
Add a basic bootstrap-data-table control

### ISSUE THREAD

**Issue by chadzink** [wildland/ember-bootstrap-controls#61]
Adding a basic bootstrap table control will help with standardizing the way we use tables in applications and make it quicker to setup.

The control will need to be easy to use and well documented. The basic idea is that we have something like:
```
{{bootstrap-data-table
  dataArray=persons
  columns=(array
    (hash
      attr="firstName"
      label="First Name"
    )
    (hash
      attr="lastName"
      label="Last Name"
    )
    (hash
      attr="email"
      label="Email"
    )
  )
}}
```

That produces a table like:
```
<tabel class="table">
  <thead>
    <tr>
      {{#each columns as |column|}}
        <th>{{column.label}}</th>
      {{/each}}
    </tr>
  </thead>
  <tbody>
    {{#each dataArray as |item|}}
      <tr>
        {{#each columns as |column|}}
          <td>{{get item column.attr}}</td>
        {{/each}}
      </tr>
    {{/each}}
  </tbody>
</table>
```

However, we would want additional options added to define the table such as defining the component like:
```
{{bootstrap-data-table
  dataArray=persons
  className="table-bordered"
  tableId="optionalTableId"
  responsive=true
  columns=(array
    (hash
      attr="firstName"
      label="First Name"
      thClassName="my-header-class"
      tdClassName="my-data-class"
    )
    (hash
      attr="lastName"
      label="Last Name"
      thClassName="my-header-class"
      tdClassName="my-data-class"
    )
    (hash
      attr="email"
      label="Email"
      thClassName="my-header-class"
      tdClassName="my-data-class"
    )
  )
}}
```
This would add in the logic to handle these options.
See: http://v4-alpha.getbootstrap.com/content/tables/ for bootstrap table info.

**Comment by flarinerin** [comment]
I think this would be a great addition to our toolbox. When I'm designing I spend a lot of time thinking of rows as components as well. Can we add an additional issue to create a row control as well?

Thanks, Chad!

**Comment by jweakley** [comment]
I think there would be a lot of value if this also added sorting to the columns and pagination automatically.
