### ISSUE TITLE
Blocker: Components do not accept an array of class string names

### ISSUE THREAD

**Issue by flarinerin** [wildland/ember-bootstrap-controls#80]
Bootstrap components need to fix classNames.

Update components to accept an array of class string names instead of just a string.

Bootstrap input needs to be addressed - it is a blocker for me on a Denovo issue.

**Comment by jweakley** [comment]
This is partially address with the use of control-wrapper.

**Comment by Samsinite** [comment]
Pretty sure this is no longer an issue
