### ISSUE TITLE
Demo Application is missing controls

### ISSUE THREAD

**Issue by temecom** [wildland/ember-bootstrap-controls#96]
Just went to show a colleague the demo controls and there is only 2 showing: checkbox and pagination. It looks like the latest commit broke something. 
http://wildland.github.io/ember-bootstrap-controls/#/?s=Bootstrap%20Controls&ss=Input

Chris

**Comment by jweakley** [comment]
As of 3/30/18 it looks like all the controls are now in the demo application.
